Deduplicate offers only on event subcategories
pass-culture/data-gcp pull request #1186
Opened 2022-12-02 17:25 UTC by lmontier

2022-12-05 15:49 UTC, dcuesta-pass submitted a review, later dismissed

2022-12-05 16:37 UTC, cdelabre requested changes

2022-12-05 16:37 UTC, cdelabre commented on orchestration/dags/common/macros.py
> +    "event_subcategories": (
Les variables via macros sont globales or ici, c'est pour un use case très particulier.
Plutôt utiliser les `params` pour mettre des variables spécifiques (par [ex](https://github.com/pass-culture/data-gcp/blob/master/orchestration/dags/dependencies/firebase/import_firebase.py#L36)

2022-12-05 16:37 UTC, cdelabre commented on orchestration/dags/dependencies/training_data/sql/tmp/deduplicate_offers.sql
> +      FROM (SELECT * EXCEPT (item_id)
On fait plutôt des `WITH ... AS` pour plus de lisibilité

2022-12-06 15:41 UTC, cdelabre submitted a review, later dismissed

2022-12-14 09:10 UTC, merged