(PC-18842) reco offres similaires mettre en place regles metier
pass-culture/data-gcp pull request #1189
Opened 2022-12-05 09:28 UTC by LucileRainteau

2022-12-05 15:42 UTC, dcuesta-pass commented on recommendation/api/src/pcreco/core/similar_offer.py
> +            user_iris_id=str(self.user.iris_id),  # user or offer iris ?
Utiliser la class 'Offer' içi à la place de 'User'

2022-12-05 16:10 UTC, cdelabre requested changes

2022-12-05 16:10 UTC, cdelabre commented on recommendation/api/src/app.py
> +    if offer.get_cnt_bookings(offer_id) > 5:
Je pense qu'il faut quand même renvoyer un résultat même s'il est vide.

Je ferai plutôt la gestion dans SimilarOffer lors du call a `get_scoring`

2022-12-05 16:10 UTC, cdelabre commented on recommendation/api/src/pcreco/core/offer.py
> +    def get_item_id(self, offer_id) -> str:
Peut-être ne faire qu'un appel à la DB (`get_item_id`) au lieu de le faire deux fois avec `get_cnt_bookings` ?

2022-12-08 17:45 UTC, cdelabre submitted a review, later dismissed

2022-12-09 09:07 UTC, merged