Create algo_training_clicks dag
pass-culture/data-gcp pull request #1198
Opened 2022-12-07 15:38 UTC by gabrielsicara

2022-12-08 11:44 UTC, lmontier requested changes

2022-12-08 11:44 UTC, lmontier commented on algo_training/data_collect.py
> +    table: str = typer.Option("bookings"),
un petit `help="..."`, pour approrter de la clarté (comme ci-dessus)

2022-12-08 11:44 UTC, lmontier commented on orchestration/dags/jobs/ml/algo_training_clicks.py
> +            --command {FETCH_CODE}
une factorisation de cette commande  
```
gcloud compute ssh {GCE_INSTANCE} \
            --zone {GCE_ZONE} \
            --project {GCP_PROJECT_ID} \
            --command 
```
? (ça apportera pas mal de clarté au DAG)

2022-12-08 14:20 UTC, gabrielsicara commented on orchestration/dags/jobs/ml/algo_training_clicks.py
> +            --command {FETCH_CODE}
en ticket 5S je l'ai mis

2022-12-08 14:26 UTC, gabrielsicara commented on algo_training/data_collect.py
> +    table: str = typer.Option("bookings"),
done

2022-12-08 15:27 UTC, lmontier approved these changes

2022-12-09 08:33 UTC, lmontier requested changes

2022-12-09 08:33 UTC, lmontier commented on algo_training/evaluate.py
> +        : min(EVALUATION_USER_NUMBER, len(positive_data_test))
ça risque de casser ça: 
`min(EVALUATION_USER_NUMBER, len(positive_data_test))`-> min(EVALUATION_USER_NUMBER, len(positive_data_test.user_id.nunique))`

2022-12-09 10:29 UTC, gabrielsicara commented on algo_training/evaluate.py
> +        : min(EVALUATION_USER_NUMBER, len(positive_data_test))
bv

2022-12-13 08:57 UTC, cdelabre submitted a review, later dismissed

2022-12-13 08:57 UTC, cdelabre commented on orchestration/dags/jobs/ml/algo_training_clicks.py
> +SIMILAR_OFFER_MODEL_NAME = f"similar_offers_{ENV_SHORT_NAME}"
not used !

2022-12-13 09:30 UTC, lmontier submitted a review, later dismissed

2022-12-13 14:18 UTC, lmontier approved these changes

2022-12-13 14:27 UTC, merged