[PC-22089] API fraud offer validation
pass-culture/data-gcp pull request #1565
Opened 2023-05-15 16:17 UTC by dcuesta-pass

2023-05-16 14:19 UTC, cdelabre commented on apps/fraud/validation/api/src/main.py
> +    model_uri=f"models:/validation_model_{ENV_SHORT_NAME}/Staging"
add params : {Staging}

2023-05-16 14:20 UTC, cdelabre commented on apps/fraud/validation/api/src/main.py
> +@app.post("/load_validation_model/")
`load_validation_model` => `load/model`

2023-05-16 14:36 UTC, cdelabre commented on apps/fraud/validation/api/src/main.py
> +@app.post("/get_validation_score")
`get_validation_score` => `model/compliance/scoring/`  ?

2023-05-16 14:38 UTC, cdelabre commented on apps/fraud/validation/api/src/pcvalidation/core/extract_embedding.py
> +    __download_img_from_url(url, f"./img_{unique_id}/{index}")
est-il nécessaire de download et pas load en RAM directement ?

2023-05-16 14:49 UTC, cdelabre reviewed
💭

2023-05-16 15:25 UTC, LucileRainteau commented on apps/fraud/validation/api/src/main.py
> +from pcvalidation.core.extract_embedding import extract_embedding
est ce qu'il y a nom plus explicite que pcvalidation ? et/ou challenger l'utilité de ce dossier ?

On pourrait avoir directement cette architecture : 

+-- src
|     -- main.py
|     +-- core
|     +-- utils
|     +-- tests

2023-05-16 15:34 UTC, LucileRainteau commented on apps/fraud/validation/api/src/main.py
> +    proba_val, proba_rej = get_prediction(model_loaded, pool)
proba_validation & proba_rejection pour + de sens et - d'abréviations ?

2023-05-17 08:31 UTC, dcuesta-pass commented on apps/fraud/validation/api/src/main.py
> +    model_uri=f"models:/validation_model_{ENV_SHORT_NAME}/Staging"
En realité on pourrait mettre 'production' en dur. Dans MLflow il y a 3 'stages': Stagging, Production, Archived mais comme on a un MLflow en ehp et un prod (et un model par env) cette notion de stage nous permet uniquement de marquer quelle est la version active du modèle.

2023-05-25 13:29 UTC, cdelabre commented on apps/fraud/validation/api/src/main.py
> +    context_logger.info("Succesful authentification")
missing "s"

2023-05-25 13:29 UTC, cdelabre reviewed
💭

2023-05-25 15:35 UTC, dcuesta-pass commented on apps/fraud/validation/api/src/pcvalidation/utils/env_vars.py
> +    "testuser": {
Naming de l'user à cadrer/fixer

2023-05-26 17:10 UTC, cdelabre commented on apps/fraud/validation/api/src/main.py
> +if ENV_SHORT_NAME == "dev":
Je ne suis pas sûr de comprendre. 
On ne souhaite pas les logs dans les autres env ?

2023-05-26 17:23 UTC, cdelabre requested changes

2023-05-26 17:23 UTC, cdelabre commented on apps/fraud/validation/api/src/main.py
> +connect_remote_mlflow(MLFLOW_CLIENT_ID)
Mettre cela dans un fichier model_handler.py afin de limiter les imports ici. 

Utiliser les startups calls.
> https://fastapi.tiangolo.com/advanced/events/#startup-event

2023-05-26 17:23 UTC, cdelabre commented on apps/fraud/validation/api/src/main.py
> +    custom_logger = CustomLogger(request)
Le logger devrait être initialisé via un import global
 
On peut rajouter un decorator aux fonctions http afin de mettre le `cloud_trace_context` de la request.
https://stackoverflow.com/questions/64497615/how-to-add-a-custom-decorator-to-a-fastapi-route

2023-05-26 17:23 UTC, cdelabre commented on apps/fraud/validation/api/src/pcvalidation/core/extract_embedding.py
> +    Extarct embedding with pretrained models
Extract

2023-05-26 17:23 UTC, cdelabre commented on apps/fraud/validation/api/src/pcvalidation/core/extract_embedding.py
> +
Mettre ici plutôt les TEXT_MODEL, IMAGE MODEL non ? 
Quitte à initialiser une classe et utiliser:
```model_preproc = ModelPreproc```
comme variable globale

2023-05-26 17:23 UTC, cdelabre commented on apps/fraud/validation/api/src/pcvalidation/core/extract_embedding.py
> +            # TODO: Once offer_name and description out of training remove HERE
Remvoe comments

2023-05-26 17:23 UTC, cdelabre commented on apps/fraud/validation/api/src/pcvalidation/core/extract_embedding.py
> +    data_analysis = data
Quelle est l'utilité?

2023-05-26 17:23 UTC, cdelabre commented on apps/fraud/validation/api/src/pcvalidation/core/extract_embedding.py
> +def _encode_img_from_url(model, url):
Si privée, mettre dans une classe.

2023-05-26 17:23 UTC, cdelabre commented on apps/fraud/validation/api/src/pcvalidation/core/extract_embedding.py
> +    data = requests.get(url).content
Quelle utilité de mettre la variable data ?

2023-05-26 17:23 UTC, cdelabre commented on apps/fraud/validation/api/src/pcvalidation/utils/data_model.py
> +    full_name: Union[str, None] = None
not used

2023-05-26 17:23 UTC, cdelabre reviewed
Quelques commentaires

2023-05-29 08:21 UTC, cdelabre commented on apps/fraud/validation/api/src/pcvalidation/utils/env_vars.py
> +def access_secret(project_id, secret_id, version_id=1, default=None):
`version="latest"` par défaut, supprimer les variables en dessous.

2023-05-29 08:23 UTC, cdelabre reviewed
💬

2023-05-31 12:03 UTC, cdelabre commented on Makefile
> +	MICROSERVICE_PATH=fraude/validation/api VENV_NAME=data-gcp-validation REQUIREMENTS_NAME=requirements.txt make install_microservice
fraude=> fraud ?

2023-06-02 08:44 UTC, cdelabre approved these changes

2023-06-05 09:32 UTC, merged