modification du partner_type, partner_type_origin ainsi que import_an…
pass-culture/data-gcp pull request #1755
Opened 2023-08-16 15:30 UTC by Jules-Arbelot

…alytics

2023-08-17 07:59 UTC, MatthieuRipollPassCulture commented on orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_cultural_partner_data.sql
> +    ,COALESCE(tagged_partners.partner_type,top_venue_per_offerer.partner_type, 'Structure non tagguée') AS partner_type
Il me semble qu'on avait dit que l'ordre pour déterminer le partner_type d'une structure était le suivant : 
- si structure tagguée --> le tag de la structure
- si structure pas tagguée MAIS avec un lieu taggué (**qu'il s'agisse du lieu le plus actif ou non**) --> le tag du lieu
- pas de tag structure ni tag lieu --> most_active_venue_type
- pas de lieu créé --> "Structure non tagguée"

2023-08-18 08:38 UTC, Jules-Arbelot commented on orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_cultural_partner_data.sql
> +    ,COALESCE(tagged_partners.partner_type,top_venue_per_offerer.partner_type, 'Structure non tagguée') AS partner_type
Et que prend-on si structure pas tagguée mais avec plusieurs lieux taggués ? -> most_active_venue_tag ?

2023-08-18 09:41 UTC, MatthieuRipollPassCulture commented on orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_cultural_partner_data.sql
> +    ,COALESCE(tagged_partners.partner_type,top_venue_per_offerer.partner_type, 'Structure non tagguée') AS partner_type
I'd say so !

2023-08-18 10:54 UTC, Jules-Arbelot commented on orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_cultural_partner_data.sql
> +    ,COALESCE(tagged_partners.partner_type,top_venue_per_offerer.partner_type, 'Structure non tagguée') AS partner_type
Parfait! Il me semble que c'est ce qui est fait ici du coup!

2023-08-25 10:19 UTC, MatthieuRipollPassCulture requested changes

2023-08-25 10:19 UTC, MatthieuRipollPassCulture commented on orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_cultural_partner_data.sql
> +)
Missing comma

2023-08-25 10:19 UTC, MatthieuRipollPassCulture commented on orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_cultural_partner_data.sql
> +)
Missing comma

2023-08-25 10:21 UTC, MatthieuRipollPassCulture requested changes

2023-08-25 10:21 UTC, MatthieuRipollPassCulture commented on orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_cultural_partner_data.sql
> +LEFT JOIN `{{ bigquery_analytics_dataset }}`.agg_partner_cultural_sector ON agg_partner_cultural_sector.partner_type = COALESCE(tagged_partners.partner_type, top_venue_per_offerer.partner_type)
Il faut mettre à jour la table agg_partner_cultural_sector (en mettant à jour la base froide) pour faire correspondre les tags de lieux à des secteurs culturels

2023-08-25 13:09 UTC, merged