Launch vm
pass-culture/data-gcp pull request #1892
Opened 2023-09-29 13:54 UTC by valoumiaou

## Describe your changes

This PR adds an airflow job to launch a vm to work on remotely
@cdelabre 

## Jira ticket number and/or notion link
TO DO repo admin: [https://passculture.atlassian.net/browse/PC-<num>](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources)
JIRA-replace_with_ticket_number
[Notion-link](paste within parenthesis)

## Type of change
- [ ] Fix (non-breaking change which corrects expected behavior)
- [ ] New fields (non-breaking change)
- [ ] New table (non-breaking change)
- [ ] Concept change (potentially breaking change which modifies fields according to new or evolving business concepts) 
- [ ] Table deletion (potentially breaking change which adds functionality/ table)
- [x] new job potentially harmful
      
## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] My code passes CI/CD tests
- [ ] I updated README.md
- [x] I have updated the dag 
- [ ] If my changes concern incremental table, I have altered their schema to accomodate with field's creation/deletion
- [ ] I have made corresponding changes to the [tables documentation](https://www.notion.so/passcultureapp/Documentation-Tables-175a397a8e854ff4a55ae4f3620dbe3b)
- [ ] I have made corresponding changes to the [fields glossary](https://www.notion.so/passcultureapp/854a436a8f1541e1b6ec2a65f8bab600?v=798024ba90404b139e5a17407a3bc604)
- [x] I will create a review on slack and ensure to specify the duration of the review task: short (<10min), medium (<30min), long (>30min)

## Added tests?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] ⏰ no, but I created a ticket

## Reviewer 
- [ ] I have thoroughly read the code and validated the changes
- [ ] I have checked and approuved the documentation

2023-09-29 14:08 UTC, cdelabre requested changes

2023-09-29 14:08 UTC, cdelabre commented on orchestration/dags/launch_vm.py
> +        else [{"name": "nvidia-tesla-t4", "count": "{{ params.gpu_count }}"}],
possible de mettre ça en var d'entrée ? (le type de VM) et rajouter un if else si le string est vide

2023-09-29 14:08 UTC, cdelabre commented on orchestration/dags/launch_vm.py
> +    description="Launch a vm to work in production environment",
pas forcément en prod

2023-09-29 14:08 UTC, cdelabre commented on orchestration/dags/launch_vm.py
> +        "prod": "n1-highmem-32",
Je serais pour laisse la "n1-standard-2" partout :)

2023-09-29 14:08 UTC, cdelabre commented on orchestration/dags/common/hooks/gce.py
> +            "labels": dict(DEFAULT_LABELS, labels),
il manque des ** ici je pense

2023-09-29 14:40 UTC, valoumiaou commented on orchestration/dags/common/hooks/gce.py
> +            "labels": dict(DEFAULT_LABELS, labels),
j'ai mis labels en variable de la methode. il faut quand meme le kwarg ?

2023-10-02 12:28 UTC, cdelabre submitted a review, later dismissed

2023-10-09 14:47 UTC, cdelabre approved these changes

2023-10-09 15:10 UTC, merged