Pc 27854 data creer une table de decouvrabilite du catalogue par mois et item
pass-culture/data-gcp pull request #2249
Opened 2024-02-07 17:34 UTC by MatthieuRipollPassCulture

### Select PR template in preview mode:
* [Hotfix](?expand=1&template=Hotfix_template.md)
* [DA](?expand=1&template=DA_ticket_template.md)
* [DE](?expand=1&template=DE_ticket_template.md)
* [DS](?expand=1&template=DS_ticket_template.md)
* [MEP](?expand=1&template=MEP_template.md)

2024-02-21 08:44 UTC, LucileRainteau commented on orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_monthly_bookable_item_discoverability.sql
> +
ajouter la config d'une query incrémentale, pour incrémenter cette table mensuellement avec les données du mois précédent ET
ajouter le filtre month = 'last_month' à la requête 
ensuite pour n'executer la requête qu'une seule fois par mois, on peut créer un script qui lance cette requête uniquement si on est le 1er du mois

2024-02-21 08:45 UTC, LucileRainteau requested changes
autre com !

2024-02-21 10:06 UTC, MatthieuRipollPassCulture commented on orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_daily_offer_consultation_data.sql
> +WHERE
Done !

2024-02-21 10:07 UTC, MatthieuRipollPassCulture commented on orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_monthly_bookable_item_discoverability.sql
> +
Done, je te laisse review !

2024-02-21 10:25 UTC, LucileRainteau reviewed
new review (on peut faire un point stu veux)

2024-02-21 10:25 UTC, LucileRainteau commented on orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_monthly_bookable_item_discoverability.sql
> +        tags = "monthly"
missing comma

2024-02-21 10:25 UTC, LucileRainteau commented on orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_monthly_bookable_item_discoverability.sql
> +  DATE(partition_date) >= DATE_SUB(DATE(_dbt_max_partition), INTERVAL 1 MONTH)
Je pense que 
DATE(partition_date) >= DATE(_dbt_max_partition)
est suffisant pour ce filtre (sauf si on veut calculer les 2 derniers mois à chaque incrément)

_dbt_max_partion prend le max de la date de partition dans la table à date (avant de l'incrémenter avec les nvles data)

Voir si nécessaire de mettre une borne de date min et max ?

2024-02-26 13:40 UTC, MatthieuRipollPassCulture commented on orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_monthly_bookable_item_discoverability.sql
> +  DATE(partition_date) >= DATE_SUB(DATE(_dbt_max_partition), INTERVAL 1 MONTH)
Done

2024-02-26 15:00 UTC, LucileRainteau approved these changes

2024-02-28 15:58 UTC, merged