Clickhouse data
pass-culture/data-gcp pull request #2547
Opened 2024-05-24 07:35 UTC by valoumiaou

# DE PR

## Describe your changes

Please include a summary of the changes:

This PR imports data in clickhouse cluster

Tag a reviewer if necessacy  @github/username 

## Jira ticket number and/or notion link

JIRA-ticket_number

### Type of change
- [ ] Fix (non-breaking change which corrects expected behavior)
- [ ] New fields (non-breaking change)
- [x] New table (non-breaking change)
- [x] Concept change (potentially breaking change which modifies fields according to new or evolving business concepts) 
- [ ] Table deletion (potentially breaking change which adds functionality/ table)
      
### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] My code passes CI/CD tests
- [ ] I updated README.md
- [x] I have updated the dag
- [ ] If my changes concern incremental table, I have altered their schema to accomodate with field's creation/deletion
- [ ] I have made corresponding changes to the [tables documentation](https://www.notion.so/passcultureapp/Documentation-Tables-175a397a8e854ff4a55ae4f3620dbe3b)
- [ ] I have made corresponding changes to the [fields glossary](https://www.notion.so/passcultureapp/854a436a8f1541e1b6ec2a65f8bab600?v=798024ba90404b139e5a17407a3bc604)
- [x] I will create a review on slack and ensure to specify the duration of the review task: short (<10min), medium (<30min), long (>30min)

### Added tests?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] ⏰ no, but I created a ticket

2024-05-24 08:59 UTC, carolinemestre-passculture commented on orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__pro_events.sql
> +-- AND event_name in ("ConsultOffer","ConsultVenue","HasAddedOfferToFavorites")
```suggestion
```

2024-05-24 08:59 UTC, carolinemestre-passculture commented on orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__bookings.sql
Pour les noms des modèles on met tout au singulier. :)

2024-05-24 09:40 UTC, cdelabre commented on orchestration/dags/dependencies/export_clickhouse/export_clickhouse.py
> +TABLES_CONFIGS2 = [
replace with old config file

2024-05-24 09:41 UTC, cdelabre requested changes

2024-05-24 09:41 UTC, cdelabre commented on orchestration/dags/jobs/export/export_clickhouse2.py
> +# SQL_BASE_PATH = Path(f"{os.environ['GCS_BUCKET']}/plugins/compiled/data_gcp_dbt/models/export/clickhouse")
remove

2024-05-24 09:41 UTC, cdelabre commented on orchestration/dags/jobs/export/export_clickhouse2.py
> +    "instance_name": f"export-clickhouse2-data-{ENV_SHORT_NAME}",
2?

2024-05-24 09:41 UTC, cdelabre commented on orchestration/dags/jobs/export/export_clickhouse2.py
> +        description="Export to analytics data posthog",
posthog ?

2024-05-24 09:41 UTC, cdelabre commented on orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__native_event.sql
> +AND MOD(ABS(FARM_FINGERPRINT(user_pseudo_id)),10) = 0
?

2024-05-24 09:41 UTC, cdelabre commented on orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__native_event.sql
> +    event_date BETWEEN date_sub(DATE("{{ ds() }}"), INTERVAL {{ var("clickhouse_day_params",4) }} DAY) and DATE("{{ ds() }}")
Quelle utilité sur une vue de forcer 4 jours?

2024-05-24 09:41 UTC, cdelabre commented on orchestration/dags/jobs/export/export_clickhouse2.py
> +                default=-30,
30 ?

2024-05-24 09:41 UTC, cdelabre commented on jobs/etl_jobs/internal/export_clickhouse/schema/analytics/daily_aggregated_event.sql
> +    sum(is_consult_offer) AS nbr_offer_consultation,
nbr?

2024-05-27 09:03 UTC, carolinemestre-passculture commented on jobs/etl_jobs/internal/export_clickhouse/schema/analytics/daily_aggregated_event.sql
> +    sum(is_consult_offer) AS nbr_offer_consultation,
`total_consultated_offers` ?

2024-06-17 13:22 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/refresh.py
@cdelabre

2024-06-17 13:26 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/schema/analytics/daily_aggregated_event.sql
@cdelabre

2024-06-17 13:26 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthy_aggregated_offerer_collective_revenue.sql
@cdelabre

2024-06-17 13:27 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthy_aggregated_offerer_revenue.sql
@cdelabre

2024-06-17 13:28 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_offerer_collective_revenue.sql
@cdelabre

2024-06-17 13:28 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/schema/intermediate/booking.sql
@cdelabre

2024-06-17 13:28 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/schema/intermediate/collective_booking.sql
@cdelabre

2024-06-17 13:29 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/schema/intermediate/native_event.sql
@cdelabre

2024-06-17 13:29 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/schema/tmp/intermediate_booking.sql
@cdelabre

2024-06-17 13:29 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/schema/tmp/intermediate_collective_booking.sql
@cdelabre

2024-06-17 13:29 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/schema/tmp/intermediate_native_event.sql
@cdelabre

2024-06-17 13:29 UTC, valoumiaou commented on jobs/etl_jobs/internal/export_clickhouse/update.py
@cdelabre

2024-06-17 13:31 UTC, valoumiaou commented on orchestration/dags/dependencies/export_clickhouse/export_clickhouse.py
@cdelabre

2024-06-17 14:11 UTC, cdelabre approved these changes

2024-06-17 16:33 UTC, cdelabre submitted a review, later dismissed

2024-06-18 09:06 UTC, merged