[PR-DATA-88] Update item linkage
pass-culture/data-gcp pull request #2720
Opened 2024-07-02 08:09 UTC by dcuesta-pass

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/model/semantic_space.py
> +        n=50,
enlever le param par défaut

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/model/semantic_space.py
> +            .refine_factor(10)
fixer les params

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/requirements.txt
> +recordlinkage==0.16
requirements.in et requirements.txt

https://www.notion.so/passcultureapp/Comment-versionner-mes-packages-python-dans-un-microservice-c47a8f5364cf4201b5ed107228188ca9

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/streamlit/st_linkage_analysis.py
> +import pandas as pd
dossier streamlit -> streamlits

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/utils/common.py
> +        json.dump(model_type, file)
à suppriemr

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/utils/common.py
> +    # return pd.DataFrame({"embedding":reduced_embeddings})
enlever le com

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/utils/common.py
> +    ldf = pl.scan_pyarrow_dataset(dataset)
ldf -> un nom compréhensible

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +            feature,
pk 2 fois feature?

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +    for feature, feature_dict in FEATURES.items():
feature -> feature_name

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +    for feature, feature_dict in FEATURES.items():
feature_dict => comparison_params

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +        candidate_links (pd.MultiIndex): Candidate links.
une petite doc pour expliquer ce candidate_links

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +    indexer = recordlinkage.index.Block(on="batch_id")
indexer -> indexes_per_candidate

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +    indexer = recordlinkage.index.Block(on="batch_id")
batch_id -> retrieval_candidates_id

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +
sources_df et candidates_df

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +    ).drop(columns=["item_id_candidate"])
à mettre dans prepare_tables

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +    """
return a single df

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +    candidates_final_clean = candidates_final.query("link_id != 'NC'")
candidates_final.loc[lambda df: df.link_id != "NC"]

2024-07-04 08:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +    candidates_final_clean = candidates_final.query("link_id != 'NC'")
comme tu veux :)

2024-07-04 08:19 UTC, lmontier-pass commented on orchestration/dags/jobs/ml/link_items.py
> +    # "on_failure_callback": task_fail_slack_alert,
à suprimer

2024-07-09 14:19 UTC, lmontier-pass requested changes

2024-07-09 14:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/build_semantic_space.py
> +        performer=lambda df: df["performer"].fillna(value="unkn"),
si tu peux ajouter ce unkn en constante. Genre: UNKNOWN_KEYWORD = "unkn" dans constant.py , puis venir l'importer ici

2024-07-09 14:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/constants.py
> +MATCHES_REQUIRED = 3
:+1:

2024-07-09 14:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +    candidates = candidates.assign(link_id="NC")
idem : Mettre le "NC" dans une constante de constants.py et l'importer ici

2024-07-09 14:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +    matches["index_2"] = matches["index_2"].apply(lambda x: f"C-{x}")
pourquoi ne pas laisser source ? C'est plus explicite que S et C non ?

2024-07-09 14:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +    matches["index_2"] = matches["index_2"].apply(lambda x: f"C-{x}")
en pandas, ça sera beaucoup plus rapide d'utiliser des opérations "vectorisées" , plutôt que des boucles for. Et en gros, les map, apply sont des boucles for déguisées. 

par exemple ici tu peux faire :

```
matches = matches.assign(
  index_1 = lambda df: "S-" + df.index_1.astype(str),
  index_2 = lambda df: "C-" + df.index_2.astype(str)
)
```

Pour savoir si tu peux vectoriser ou non, il faut se poser la question; est-ce que mon opération va dépendre de la valeur d'un champ de ma ligne, ou est ce que je peux appliquer une opération globale à une colonne ? (genre ici, on concatène une colonne avec un string => c'est donc vectorisable)

2024-07-09 14:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
>                  sources.at[index, "link_id"] = str(link_id)
cf plus haut, remettre source

2024-07-09 14:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +        .fillna(value="no_name"),
idem: à mettre dans une constante

2024-07-09 14:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +        .fillna(value="no_des"),
idem, à mettre dans une constante

2024-07-09 14:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/link_items.py
> +        .fillna(value="unkn"),
tu peux aussi faire une fonction : 
```
def format_series(series: pd.Series, na_value: str):
   return series.replace("", None).str.lower().fillna(value=na_value))
```

puis ensuite faire dans le assign 

`performer= lambda df: df.performer.map(format_series, na_value="unkn"), offer_name=...)`

2024-07-09 14:19 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/streamlits/st_linkage_analysis.py
> +    "gs://mlflow-bucket-prod/linkage_item_prod/linkage_20240625T084628/linkage_final_items_sources.parquet"
on est d'accord, les buckets sont bien privés?

2024-07-09 14:19 UTC, lmontier-pass commented on orchestration/dags/jobs/ml/link_items.py
> +    # "on_failure_callback": task_fail_slack_alert,
à supprimer (et non à commenter)

2024-07-09 14:19 UTC, lmontier-pass commented on orchestration/dags/jobs/ml/link_items.py
>          dag=dag,
:+1

2024-07-09 14:32 UTC, lmontier-pass commented on jobs/ml_jobs/item_linkage/build_semantic_space.py
> +    """
je rennomerai la fonction en preprocess_data_and_store_reducer(gcs_path: str, column_name_list, reducer_path: str)

parce qu'on ne sait plus trop où est-ce que l"'on sauvegarde ce modèle...

2024-07-09 14:32 UTC, lmontier-pass commented on jobs/ml_jobs/retrieval_vector/app/model.py
>          return Document(embedding=reduce)
c'est pas utilisé non?

2024-07-09 14:32 UTC, lmontier-pass commented on orchestration/dags/dependencies/ml/linkage/sql/linkage_item_candidates_data.sql
> +QUALIFY ROW_NUMBER() OVER (PARTITION BY offer_id ORDER BY performer DESC) = 1
j'avoue que ce n'est pas très clair pour moi cette Query. Si t'es sur de toi fine, sinon tu peux me l'expliquer

2024-07-09 14:32 UTC, lmontier-pass commented on orchestration/dags/dependencies/ml/linkage/sql/linkage_item_sources_data.sql
> +    SELECT
idem

2024-07-15 08:41 UTC, cdelabre commented on orchestration/dags/jobs/ml/link_items.py
> +    # "on_failure_callback": task_fail_slack_alert,
(à garder plutôt pour avoir les alertes)

2024-07-15 09:10 UTC, lmontier-pass approved these changes

2024-07-15 09:13 UTC, cdelabre commented on orchestration/dags/jobs/ml/link_items.py
> +    # "on_failure_callback": task_fail_slack_alert,
à remettre une fois le code en production

2024-07-15 09:14 UTC, merged