[PR-DE-386] feat: Add product_extra_data column to product.sql and up…
pass-culture/data-gcp pull request #2764
Opened 2024-07-08 16:27 UTC by dcuesta-pass

…date item_group_by_product_id in offer_item_ids.sql

# DE PR

## Describe your changes

Add product_extra_data to product table 

update offer_extracted_data pour prendre la compte la non duplication des extra data d'une offre si elle est associé à un Product

Update offer_item_ids : 
* On ne place plus par les offer_extra_data pour construire l'item_id des offres synchro , on se repose directement sur l'offer_product_id 

This PR adds the feature

Tag a reviewer if necessacy  @github/username 

### Type of change
- [ ] Fix (non-breaking change which corrects expected behavior)
- [x] New fields (non-breaking change)
- [x] New table (non-breaking change)
- [x] Concept change (potentially breaking change which modifies fields according to new or evolving business concepts) 
- [ ] Table deletion (potentially breaking change which adds functionality/ table)
      
### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] My code passes CI/CD tests
- [] I have made corresponding changes to the [tables documentation](https://www.notion.so/passcultureapp/Documentation-Tables-175a397a8e854ff4a55ae4f3620dbe3b)
- [ ] I have made corresponding changes to the [fields glossary](https://www.notion.so/passcultureapp/854a436a8f1541e1b6ec2a65f8bab600?v=798024ba90404b139e5a17407a3bc604)
- [x] I will create a review on slack and ensure to specify the duration of the review task: short (<10min), medium (<30min), long (>30min)

### Added tests?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help
- [ ] ⏰ no, but I created a ticket

2024-07-09 07:32 UTC, cdelabre commented on orchestration/dags/data_gcp_dbt/models/clean/offer_item_ids.sql
> +        CONCAT('product-',COALESCE(offer.offer_id, offer.offer_product_id)) as item_id,
l'inverse non ?

2024-07-09 07:32 UTC, cdelabre commented on orchestration/dags/data_gcp_dbt/models/clean/offer_item_ids.sql
>                  r'[^a-zA-Z0-9\-\_]',
On peut supprimer les regex je pense

2024-07-09 07:34 UTC, cdelabre reviewed
quelques commentaires

2024-07-09 13:29 UTC, carolinemestre-passculture approved these changes

2024-07-09 13:29 UTC, carolinemestre-passculture commented on orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__extract_offer.sql
> +)
```suggestion
),
```

2024-07-09 13:29 UTC, carolinemestre-passculture commented on orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__extract_offer.sql
> +LEFT JOIN unified_extra_data AS ued on ued.offer_id=offer.offer_id
On pourrait supprimer la première sub query et faire tout en une sub query au début, un truc comme ça : 
```
SELECT [..],
LOWER(TRIM...)
COALESCE(product_extra_data,offer_extra_data) as unified_extra_data
FROM {{ source('raw', 'applicative_database_offer') }} AS offer
LEFT JOIN {{ source('raw', 'applicative_database_product') }} AS product on product.id=offer.offer_product_id
```

2024-07-09 13:29 UTC, carolinemestre-passculture commented on orchestration/dags/data_gcp_dbt/models/clean/offer_item_ids.sql
>  )
Pareil j'ai l'impression qu'on pourrait facilement faire ces deux queries en une seule sans que ça enlève de la clarté dans la lecture

2024-07-09 13:31 UTC, carolinemestre-passculture commented on orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__extract_offer.sql
> +  COALESCE(product_extra_data,offer_extra_data) as unified_extra_data
Ce nom de colonne ne me semble pas très clair

2024-07-09 13:40 UTC, dcuesta-pass commented on orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__extract_offer.sql
> +LEFT JOIN unified_extra_data AS ued on ued.offer_id=offer.offer_id
Si tu fais le coalesce après le JSON_EXTRACT comment il sait sur quelle json le faire. Ou alors le sens n'a pas d'importance ?

2024-07-09 13:53 UTC, dcuesta-pass commented on orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__extract_offer.sql
> +  COALESCE(product_extra_data,offer_extra_data) as unified_extra_data
et simplement 'extra_data' ? ou pas assez distinctif ?

2024-07-11 13:25 UTC, valoumiaou requested changes

2024-07-11 13:25 UTC, valoumiaou commented on orchestration/dags/data_gcp_dbt/models/clean/offer_extracted_data.sql
> +offer.offer_id,
booking email manquant

2024-07-11 15:21 UTC, valoumiaou approved these changes

2024-07-11 15:27 UTC, merged