(dbt) Factorize logs models
pass-culture/data-gcp pull request #3184
Opened 2024-09-20 13:33 UTC by carolinemestre-passculture

# DE PR

## Describe your changes

Please include a summary of the changes:

This PR [adds/removes/fixes/replaces] the [feature/bug/etc]. 

Tag a reviewer if necessacy  @github/username 

## Jira ticket number and/or notion link

JIRA-ticket_number

### Type of change
- [ ] Fix (non-breaking change which corrects expected behavior)
- [ ] New fields (non-breaking change)
- [ ] New table (non-breaking change)
- [ ] Concept change (potentially breaking change which modifies fields according to new or evolving business concepts) 
- [ ] Table deletion (potentially breaking change which adds functionality/ table)
      
### Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] My code passes CI/CD tests
- [ ] I updated README.md
- [ ] I have updated the dag
- [ ] If my changes concern incremental table, I have altered their schema to accomodate with field's creation/deletion
- [ ] I have made corresponding changes to the [tables documentation](https://www.notion.so/passcultureapp/Documentation-Tables-175a397a8e854ff4a55ae4f3620dbe3b)
- [ ] I have made corresponding changes to the [fields glossary](https://www.notion.so/passcultureapp/854a436a8f1541e1b6ec2a65f8bab600?v=798024ba90404b139e5a17407a3bc604)
- [ ] I will create a review on slack and ensure to specify the duration of the review task: short (<10min), medium (<30min), long (>30min)

### Added tests?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] ⏰ no, but I created a ticket

2024-09-30 13:03 UTC, cdelabre requested changes

2024-09-30 13:03 UTC, cdelabre commented on orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__user.sql
>  with themes_subscribed as (
Ce calcul me semble coûteux et peu critique. Est-il indispensable ? N'y a-t-il pas une table côté backend pour avoir cette information plutôt que via des logs ?

2024-09-30 13:15 UTC, carolinemestre-passculture commented on orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__backoffice_log.sql
> +    AND DATE(log_timestamp) >= DATE_SUB(DATE('{{ ds() }}'), interval 7 day)
Je sais pas pour ça, j'ai repris le modèle de base mais si c'est pas utile on peut en effet retirer cette partie. Qui est le référent DA de ce modèle ?

2024-09-30 13:48 UTC, cdelabre commented on orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__backoffice_log.sql
> +    AND DATE(log_timestamp) >= DATE_SUB(DATE('{{ ds() }}'), interval 7 day)
@mathilde-vey  ?

2024-09-30 16:08 UTC, cdelabre submitted a review, later dismissed

2024-10-07 10:26 UTC, cdelabre commented on orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__backoffice_log.sql
> +    AND DATE(log_timestamp) >= DATE_SUB(DATE('{{ ds() }}'), interval 7 day)
Vu avec @mathilde-vey , on passe à 2 J

2024-10-07 10:27 UTC, merged