De 565/VMs uv install
pass-culture/data-gcp pull request #3219
Opened 2024-10-01 11:16 UTC by valoumiaou

# DE PR

## Describe your changes

Please include a summary of the changes:

This PR [adds/removes/fixes/replaces] the [feature/bug/etc]. 

Tag a reviewer if necessacy  @github/username 

## Jira ticket number and/or notion link

JIRA-ticket_number

### Type of change
- [ ] Fix (non-breaking change which corrects expected behavior)
- [ ] New fields (non-breaking change)
- [ ] New table (non-breaking change)
- [ ] Concept change (potentially breaking change which modifies fields according to new or evolving business concepts) 
- [ ] Table deletion (potentially breaking change which adds functionality/ table)
      
### Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] My code passes CI/CD tests
- [ ] I updated README.md
- [ ] I have updated the dag
- [ ] If my changes concern incremental table, I have altered their schema to accomodate with field's creation/deletion
- [ ] I have made corresponding changes to the [tables documentation](https://www.notion.so/passcultureapp/Documentation-Tables-175a397a8e854ff4a55ae4f3620dbe3b)
- [ ] I have made corresponding changes to the [fields glossary](https://www.notion.so/passcultureapp/854a436a8f1541e1b6ec2a65f8bab600?v=798024ba90404b139e5a17407a3bc604)
- [ ] I will create a review on slack and ensure to specify the duration of the review task: short (<10min), medium (<30min), long (>30min)

### Added tests?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] ⏰ no, but I created a ticket

2024-10-01 12:48 UTC, lmontier-pass requested changes

2024-10-01 12:48 UTC, lmontier-pass commented on orchestration/dags/jobs/import/import_addresses.py
>      },
:heart

2024-10-01 12:48 UTC, lmontier-pass commented on orchestration/dags/jobs/import/import_addresses.py
>          python_version="3.10",
il n'y a plus le base_dir?

2024-10-01 12:48 UTC, lmontier-pass commented on orchestration/dags/common/operators/gce.py
> +            return ":".join(filtered_paths) + ":+$PATH"
de ce que je comprends, cette fonction est là pour gérer le cas du PATH: ... dans la variable DEFAULT_EXPORT .

A mon avis, on peut faire simple, comme virer le         
"PATH": "/opt/conda/bin:/opt/conda/condabin:+$PATH", de cette variable, et l'ajouter juste dans le cas conda.

Là on créé un peu de dette avec une fonction spécifique qui vise à disparaitre

2024-10-01 12:48 UTC, lmontier-pass commented on orchestration/dags/common/operators/gce.py
> +            )
à factoriser une fois qu'on a redéfini les variables comme il faut

2024-10-01 12:48 UTC, lmontier-pass commented on orchestration/dags/common/operators/gce.py
> +            return ":".join(filtered_paths) + ":+$PATH"
je verrai qqch comme : 

```
DEFAULT_EXPORT = {
        "ENV_SHORT_NAME": ENV_SHORT_NAME,
        "GCP_PROJECT_ID": GCP_PROJECT_ID,
    }
```

```
et CONDA_EXPORT = {
        **DEFAULT_EXPORT,
        "PATH": "/opt/conda/bin:/opt/conda/condabin:+$PATH"
    }
```

2024-10-01 16:08 UTC, lmontier-pass reviewed
Quelques petits retours mais sinon c'est top

2024-10-01 16:08 UTC, lmontier-pass commented on orchestration/README.md
>  ```sh
:heart:

2024-10-01 16:08 UTC, lmontier-pass commented on orchestration/dags/common/operators/gce.py
>              )
du coup tu peux faire 
```
 commands_list.append(
            "\n".join(
                [
                    f"export {key}={value}"
                    for key, value in self.environment.items()
                ])
``` 

non?

2024-10-01 16:08 UTC, lmontier-pass commented on orchestration/dags/common/operators/gce.py
> +        repo_dir = "data-gcp"
* je l'aurais en déclaré en constante plutot 
* ROOT_REPO_DIR  ? repo_dir je ne trouve pas ça si clair

2024-10-02 07:36 UTC, lmontier-pass submitted a review, later dismissed
On est d'accord, tu as testé que :
1. import_adresses fonctionne bien ?
2.  et qu'un des autres DAGs fonctionne encore ?

2024-10-02 07:36 UTC, lmontier-pass commented on orchestration/dags/common/operators/gce.py
> +        installer: str = "uv",  # Default to 'uv'
plus une suggestion de bonne pratique qu'un vrai retour car à terme ce paramètre va disparaître . 
Mais ici, ça aurait été cool de mettre un ENUM en type ("uv" ou "conda") histoire de fermer les conditions possibles

2024-10-02 12:51 UTC, valoumiaou commented
> On est d'accord, tu as testé que :
> 
> 1. import_adresses fonctionne bien ?
> 2. et qu'un des autres DAGs fonctionne encore ?

oui

2024-10-02 14:43 UTC, lmontier-pass approved these changes

2024-10-02 14:44 UTC, merged