Pc 9692 extract tags bis
pass-culture/data-gcp pull request #387
Opened 2021-07-21 14:28 UTC by dcuesta-pass

2021-07-21 14:30 UTC, danslama2310 approved these changes

2021-07-21 14:31 UTC, danslama2310 approved these changes

2021-07-21 15:13 UTC, danslama2310 approved these changes

2021-07-27 12:46 UTC, danslama2310 approved these changes

2021-07-27 12:46 UTC, danslama2310 approved these changes

2021-07-27 12:46 UTC, danslama2310 submitted a review, later dismissed

2021-07-27 13:30 UTC, bourliam requested changes

2021-07-27 13:30 UTC, bourliam commented on orchestration/dags/dependencies/tag_offers.py
> +def TagDescriptions(offers_to_tag, TopicList):
tag_descriptions plutôt

2021-07-27 13:30 UTC, bourliam commented on orchestration/dags/extract_offer_tags.py
> +    "start_date": airflow.utils.dates.days_ago(0),
il faut mettre une start date "en dur" cf les autres dags

2021-07-27 13:30 UTC, bourliam commented on orchestration/dags/extract_offer_tags.py
> +    schedule_interval=None,
si il y a pas de schedule_interval le dag ne tournera jamais

2021-07-27 16:06 UTC, danslama2310 approved these changes

2021-07-27 16:06 UTC, danslama2310 approved these changes

2021-07-27 16:07 UTC, danslama2310 approved these changes

2021-07-27 16:08 UTC, danslama2310 approved these changes

2021-07-27 16:09 UTC, danslama2310 approved these changes

2021-07-27 16:09 UTC, danslama2310 approved these changes

2021-07-28 07:16 UTC, bourliam requested changes

2021-07-28 07:16 UTC, bourliam commented on orchestration/dags/dependencies/tag_offers.py
> +def Tag_Descriptions(offers_to_tag, TopicList):
Il ne faut pas mettre de majuscules aux fonctions, donc plutôt "tag_descriptions"

2021-07-28 07:31 UTC, bourliam approved these changes

2021-07-28 07:44 UTC, merged